name: "QAWolf Greenlight"
description: "Triggers a test suite run and waits for the results from QAWolf"
branding:
  icon: 'bell'
  color: 'blue'
inputs:
  qawolf-api-key:
    description: "API Key on QAWolf"
    required: true
  qawolf-notification-config:
    description: "DeployConfig for QAWolf.attemptNotifyDeploy."
    required: true
    default: "{}"
  timeout:
    description: "Timeout in seconds"
    default: 600
  interval:
    description: "Interval to check for status"
    default: 30
outputs:
  status:
    description: "The status of the test run. 'success' or 'failure' or 'timeout' or 'cancelled'"
    value: ${{ steps.triggerRun.outputs.status }}
  blockingBugsCount:
    description: "The number of blocking bugs"
    value: ${{ steps.triggerRun.outputs.blockingBugsCount }}
  nonBlockingBugsCount:
    description: "The number of non-blocking bugs"
    value: ${{ steps.triggerRun.outputs.nonBlockingBugsCount }}
  numWorkflowsRun:
    description: "The number of workflows run"
    value: ${{ steps.triggerRun.outputs.numWorkflowsRun }}
  bugs:
    description: "The number of reproduced bugs in JSON format"
    value: ${{ steps.triggerRun.outputs.bugs }}
runs:
  using: "composite"
  steps:
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - id: triggerRun
      shell: bash
      working-directory: ${{ github.action_path }}
      run: node ./index.js
      env:
        INPUT_API_KEY: ${{ inputs.qawolf-api-key }}
        INPUT_CONFIG: ${{ inputs.qawolf-notification-config }}
        INPUT_TIMEOUT: ${{ inputs.timeout }}
        INPUT_INTERVAL: ${{ inputs.interval }}
